#
#   Defines
#
BASEDIR		:=	../

CFLAGS		:=

INCLUDES    := -I./

LIBS		:= -lpthread -rdynamic

LDFLAGS		:=

APPEND_OBJS	:=

SUBDIRS		:=

#USERDEFS	:= -D_ANDROID_BUILD


#
#   Target object
#
TARGET_NAME	:=	immsocketcommon

#
#   Target type
#     (EXEC/SHARED/STATIC/OBJECT)
#
TARGET_TYPE	:=	SHARED

#
#   Compile sources
#
SRCS		:=

SRCS_CPP	:= \
	Utils.cpp \
	WorkerThread.cpp \
	SigwaitThread.cpp \

#
#   Configurations
#
include $(BASEDIR)/Config.make

