#
#   Defines
#
BASEDIR		:=	../../

INCLUDES    := -I./

LIBS		:= -lpthread

LDFLAGS		:=

APPEND_OBJS	:=

SUBDIRS		:=

USERDEFS	:=

#
#   Target object
#
TARGET_NAME	:=	send_test

#
#   Target type
#     (EXEC/SHARED/STATIC/OBJECT)
#
TARGET_TYPE	:=	EXEC

#
#   Compile sources
#
SRCS		:=

SRCS_CPP	:= main.cpp

#
#   Configurations
#
include $(BASEDIR)/Config.make

